<?php
/**
 * Copyright © 2015 Magento. All rights reserved.
 * See COPYING.txt for license details.
 */

// @codingStandardsIgnoreFile

?>

<?php
/** @var \Magento\Catalog\Pricing\Render\FinalPriceBox $block */

$productId = $block->getSaleableItem()->getId();

/** @var \Magento\Catalog\Pricing\Price\RegularPrice $priceModel */
$priceModel = $block->getPriceType('regular_price');

/** @var \Magento\Catalog\Pricing\Price\FinalPrice $finalPriceModel */
$finalPriceModel = $block->getPriceType('final_price');
$idSuffix = $block->getIdSuffix() ? $block->getIdSuffix() : '';
$schema = ($block->getZone() == 'item_view') ? true : false;
?>
<?php if ($block->hasSpecialPrice()): ?>
    <span class="special-price">
        <?php /* @escapeNotVerified */ echo $block->renderAmount($finalPriceModel->getAmount(), [
            'display_label'     => __('Special Price'),
            'price_id'          => $block->getPriceId('product-price-' . $idSuffix),
            'price_type'        => 'finalPrice',
            'include_container' => true,
            'schema' => $schema
        ]); ?>
    </span>
    <span class="old-price">
        <?php /* @escapeNotVerified */ echo $block->renderAmount($priceModel->getAmount(), [
            'display_label'     => __('Regular Price'),
            'price_id'          => $block->getPriceId('old-price-' . $idSuffix),
            'price_type'        => 'oldPrice',
            'include_container' => true,
            'skip_adjustments'  => true
        ]); ?>
    </span>
<?php else: ?>
    <?php /* @escapeNotVerified */ echo $block->renderAmount($finalPriceModel->getAmount(), [
        'price_id'          => $block->getPriceId('product-price-' . $idSuffix),
        'price_type'        => 'finalPrice',
        'include_container' => true,
        'schema' => $schema
    ]); ?>
<?php endif; ?>

<?php if ($block->showMinimalPrice()): ?>
    <?php if ($block->getUseLinkForAsLowAs()):?>
        <a href="<?php /* @escapeNotVerified */ echo $block->getSaleableItem()->getProductUrl(); ?>" class="minimal-price-link">
            <?php /* @escapeNotVerified */ echo $block->renderAmountMinimal(); ?>
        </a>
    <?php else:?>
        <span class="minimal-price-link">
            <?php /* @escapeNotVerified */ echo $block->renderAmountMinimal(); ?>
        </span>
    <?php endif?>
<?php endif; ?>


<?php  $timeToCount = $block->timeToCount();

$helper = $this->helper('Bluecom\PriceCountDown\Helper\Data');
?>

<?php if ($helper->isCustomBlockEnabled()): ?>
    <?php if ($timeToCount>0): ?>

        <style>
            .clock{
                zoom:<?= $helper->BlockWidth() ? $helper->BlockWidth() : '0.45' ?>;
                -moz-transform: <?= $helper->BlockWidth() ? $helper->BlockWidth() : '0.45' ?>;;
                background: <?= $helper->BlockColor() ? $helper->BlockColor() : 'white' ?>;

            }
        </style>
        <div class="clock" style="margin:2em;"></div>
        <div class="message"></div>

        <script type="text/javascript">
            require(['jquery', 'countdown'], function ($) {

                $(document).ready(function() {
                    var clock;
                    clock = $('.clock').FlipClock({
                        clockFace: 'DailyCounter',
                        autoStart: false,
                        callbacks: {
                            stop: function() {
                                $('.message').html('The clock has stopped!')
                            }
                        }
                    });
                    clock.setTime(<?= $timeToCount ?>);
                    clock.setCountdown(true);
                    clock.start();
                });
            });
        </script>
    <?php endif; ?>
<?php endif; ?>




