<?php
$storeLocatorHelper = $this->helper('Bluecom\StoreLocator\Helper\Data');
?>
<h1><?php echo __('Find a store') ?></h1>
<div class="container-map">
    <div id="list">
        <ul id="ul-list" 
            data-enable="<?php echo $storeLocatorHelper->isEnabled() ?>" 
            data-mapzoom="<?php echo $storeLocatorHelper->getMapZoom() ?>">
        <?php foreach ($block->getLocations() as $location): ?>
            <li class="location-item" 
                data-longitude="<?php echo $location->getLongitude() ?>" 
                data-latitude="<?php echo $location->getLatitude() ?>" 
                data-title="<?php echo $location->getTitle() ?>" 
                data-address="<?php echo $location->getAddress() ?>" 
                data-phone="<?php echo $location->getPhone() ?>">
                <p class="item-title">
                    <a><?php echo $location->getTitle() ?></a>
                </p>
                <p><?php echo $location->getAddress() . '<br>Phone: ' . $location->getPhone() ?></p>
            </li>
        <?php endforeach; ?>
        </ul>
    </div>
    <div id="map"></div>
    <input type="text" id="addressInput" class="controls" placeholder="Search Box" />
</div>
<script src="https://maps.googleapis.com/maps/api/js?libraries=places&callback=initAutocomplete"></script>
