<style>
.container-map {
    clear: both;
    overflow: hidden;
}
#list {
    width: 25%;
    height: 500px;
    overflow: scroll;
    float: left;
}
#map {
    width: 75%;
    height: 500px;
    background-color: #CCC;
}
.item-title {
    cursor: pointer;
}
</style>

<h1><?php echo __('Find a store') ?></h1>

<div class="container-map">
    <div id="list">
        <ul id="ul-list">
        <?php foreach ($block->getLocations() as $location): ?>
            <li class="location-item" 
                data-longitude="<?php echo $location->getLongitude() ?>" 
                data-latitude="<?php echo $location->getLatitude() ?>" 
                data-title="<?php echo $location->getTitle() ?>" 
                data-address="<?php echo $location->getAddress() ?>" 
                data-phone="<?php echo $location->getPhone() ?>">
                <p class="item-title">
                    <a><?php echo $location->getTitle() ?></a>
                </p>
                <p><?php echo $location->getAddress() . '<br>Phone: ' . $location->getPhone() ?></p>
            </li>
        <?php endforeach; ?>
        </ul>
    </div>
    <div id="map"></div>
</div>

<script src="https://maps.googleapis.com/maps/api/js"></script>
<script>
    function initialize()
    {
        var defaultLoc = new google.maps.LatLng(10.8034919, 106.6161219);

        var mapCanvas = document.getElementById('map');
        var mapOptions = {
            center: defaultLoc,
            zoom: 13,
            mapTypeId: google.maps.MapTypeId.ROADMAP
        }
        var map = new google.maps.Map(mapCanvas, mapOptions);

        showLocations(map);
    }
    
    function showLocations(map)
    {
        var locs = document.getElementById('ul-list').children;
        Array.prototype.forEach.call(locs, function(el, i){
            var position = new google.maps.LatLng(
                el.getAttribute('data-longitude'), 
                el.getAttribute('data-latitude'));

            var marker = new google.maps.Marker({
                position: position,
                map: map,
                title: el.getAttribute('data-title')
            });

            var contentString = '<strong>' + el.getAttribute('data-title') + '</strong><br />' + 
                el.getAttribute('data-address') + '<br />' + 
                el.getAttribute('data-phone');

            var infowindow = new google.maps.InfoWindow({
                content: contentString
            });

            google.maps.event.addListener(marker, 'click', function() {
                infowindow.open(map, marker);
            });

            el.addEventListener('click', function() {
                var position = new google.maps.LatLng(
                    el.getAttribute('data-longitude'), 
                    el.getAttribute('data-latitude'));

                map.setCenter(position);
            });
        });
    }
    
    google.maps.event.addDomListener(window, 'load', initialize);
</script>
